# https://gitlab.freedesktop.org/NetworkManager/NetworkManager
# it requires glib; link it statically
# crypto=gnutls polkit=false
# https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/main/meson_options.txt
# change the path of /etc/resolv.conf generated by network manager
# is /etc/hosts required?

# wpa_supplicant or iwd (without dhcp)

# https://gitlab.freedesktop.org/mobile-broadband/ModemManager

# https://gitlab.freedesktop.org/geoclue/geoclue
# libgeoclue=false introspection=false gtk-doc=false
# wifi-source=false wifi-source=false 3g-source=false ip-source=false 
# avahi-glib: build and statically link

# https://github.com/eggert/tz
# only produce "right" timezones
# doas rules

# echo '#!/bin/sh
# tz check
# ' > /etc/NetworkManager/dispatcher.d/09-dispatch-script
# chmod 755 /etc/NetworkManager/dispatcher.d/09-dispatch-script
